import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

// Пример экспорта шрифтов из Google Fonts
const noto_sans = Noto_Sans({ subsets: ['latin', 'cyrillic'] });

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Тестовый проект',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className={noto_sans.className}>{children}</body>
    </html>
  );
}
